name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  release:
    uses: sanity-io/.github/.github/workflows/changesets.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      versionPrTitle: 'chore: version packages'
      versionCommitMessage: 'chore: version packages'
    secrets: inherit
